apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sds9aaky6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sds9aaky6-java-quarkus-gitops